version: '3.2'
services:
  activemq
    image: rmohr/activemq:5.14.5
    networks:
      - jms_test
    ports:
      - "1883:1883"
  producer:
    build:
      context: ./producer
    networks:
      - jms_test
networks:
  jms_test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24 
