version: '3.2'
services:
  activemq:
    image: rmohr/activemq:5.14.5
    networks:
      jms_test:
        ipv4_address: 10.0.2.10
    ports:
      - "1883:1883"
      - "8161:8161"
      - "61616:61616"
  producer:
    build:
      context: ./producer/test-producer/
    networks:
      jms_test:
        ipv4_address: 10.0.2.20
    volumes:
      - ~/.m2:/root/.m2
  mongodb1:
    image: mongo
    ports:
      - "27017"
    networks:
      jms_test:
        ipv4_address: 10.0.2.30
    command: ["mongod", "--replSet", "demo", "-dbpath", "/data/db", "--port", "27017"]
    volumes:
      - ./mongo_1:/data/db
  mongodb2:
    image: mongo
    ports:
      - "27017"
    networks:
      jms_test:
        ipv4_address: 10.0.2.31
    command: ["mongod", "--replSet", "demo", "-dbpath", "/data/db", "--port", "27017"]
    volumes:
      - ./mongo_2:/data/db
  arbiter:
    image: mongo
    ports:
      - "27017"
    networks:
      jms_test:
        ipv4_address: 10.0.2.32
    command: ["mongod", "--replSet", "demo", "-dbpath", "/data/db", "--port", "27017"]
    volumes:
      - ./mongo_3:/data/db
  mongo_cli:
    networks:
      jms_test:
        ipv4_address: 10.0.2.39
    build:
      context: ./mongodb/cli/
    command: ["sh", "mongocli.sh"]
networks:
  jms_test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24 
